### ISSUE TITLE
Topics not published when using stereo launch file

### ISSUE THREAD

**Issue by aorait** [srv/avt_vimba_camera#13]
I am using 2 GigE cameras with the stereo launch files provide. When I use the two_nodes version none of the topics seems to be published consistently. The same thing happpens with the one_node version as well. The left image showed up for 5-10 secs but then it stopped getting published. Both cameras work fine with the monocular launch file.Could you tell me why this is so? I haven't calibrated the cameras yet, but atleast the images should show up individually. 

I get the following warning messages during launch. I don't know how significant they are

[ WARN] [1467997479.870309797]: [/stereo/left]: Could not get feature BinningHorizontal
 Error: Not found.
[ WARN] [1467997479.871424693]: [/stereo/left]: Could not get feature BinningVertical
 Error: Not found.
[ WARN] [1467997479.886036724]: [/stereo/right]: Could not get feature BinningHorizontal
 Error: Not found.
[ WARN] [1467997479.887529901]: [/stereo/right]: Could not get feature BinningVertical
 Error: Not found.
[ WARN] [1467997479.940262297]: [/stereo/left]: Feature PixelFormat is available now.
[ WARN] [1467997479.945984849]: [/stereo/right]: Feature PixelFormat is available now.
[ WARN] [1467997479.991399224]: [/stereo/right]: Feature TriggerDelayAbs is not writable.

**Comment by miquelmassot** [comment]
Hi @aorait! Our stereo system is sync'ed with a cable going from the left camera to the right one. Left camera captures frames continuously and the right camera only when it receives a pulse on the digital input pin. Therefore, if the cameras are not connected (hardware synchronisation), only the left camera will stream. Which configuration do you have?

I also set up many different parameters available to dynamic reconfigure from the VIMBA manual, but not all cameras accept them. That is why you see the Not found errors.

**Comment by aorait** [comment]
@miquelmassot Thanks for your reply. I have two Manta GigE cameras.  I was trying to synchronize using software triggers. Have you tried it? Is it advisable?

**Comment by miquelmassot** [comment]
I tried and the images are obviously not in sync. If there are slow motions and dynamics, it might be ok. If you have easy access to the cameras and you can afford mounting this cable, I'd go for it.

**Comment by aorait** [comment]
The hardware synchronization works great.. Thanks!
