### ISSUE TITLE
ARMv7 still thrown

### ISSUE THREAD

**Issue by AlexisTM** [srv/avt_vimba_camera#16]
Dear @josepqp,

CMake still throw armv7  at commit 55877bddf14dd5699662fd61478d421d68bfbc04 architecture, due to [line 63](https://github.com/srv/avt_vimba_camera/blob/kinetic/CMakeLists.txt#L63). 

Bypassed by adding at line 62 : 

```
    elseif("${ARCH}" STREQUAL armv7)
      target_link_libraries(${arg}
        ${catkin_LIBRARIES}
        ${CMAKE_CURRENT_SOURCE_DIR}/lib/arm_32bit/libVimbaC.so
        ${CMAKE_CURRENT_SOURCE_DIR}/lib/arm_32bit/libVimbaCPP.so
      )
```

**Comment by miquelmassot** [comment]
Should be solved with last PR (#17).

**Comment by AlexisTM** [comment]
Thanks :D 

NOTE : Tested and working for the 4ece0eec6ba999bab9dc2b2d3bbed9939eea32c6 commit on ROS indigo, under ubuntu 14.04 on the Odroid XU4 (armv7).

The image was not "good", luminosity was flickering, but I think this is just a parameter.

**Comment by miquelmassot** [comment]
@AlexisTM are you using fluorescent light?

**Comment by AlexisTM** [comment]
Not at all. Yet, the camera worked well on Windows, with Vimba Viewer. 

The problem could be : MTU which was not updated, camera parameters or 50Hz flickering. I will investigate later.

**Comment by AlexisTM** [comment]
Problem resolved, the default exposure is 1000µS, which make oscillating luminosity due to the 50Hz of the alimentation of the neons.

Putting 10000µS corrects the problem.

**Comment by miquelmassot** [comment]
Thanks for reporting, @AlexisTM !

**Comment by josepqp** [comment]
@AlexisTM which Prosilica camera are you using ? Gigabit Ethernet ?
I'm using a Gigabit Prosilica GC1380 on a Nvidia Jetson PC (Ubuntu 14.04 32 bits), and I have problems when I visualize images, basically it returns unexpected image size. Is it working ok for you ?

**Comment by AlexisTM** [comment]
I am using a MakoG 131B with GigE.

If there is an error like : "Image is wrongly formed: step < width \* byte_depth \* num_channels", then maybe you have set a too high streamrate for your connexion. 

Are you sure the Jetson have Gigabit Ethernet?

**Comment by josepqp** [comment]
Yes it's Gigabit for sure, it's on the data-sheet and also I check it on the system.

I tried different values, but didn't worked.
I contacted AVT, and they told me that soon they will publish a new AVT ARM 64 bits driver. I hope with the 64 bits system and driver it will work. For the moment I'm developing code using an x86_64 laptop.

**Comment by AlexisTM** [comment]
ARM 64 bits drivers won't help you, because you have a 32 bits ARM. The library won't launch at all.

Personnaly, I still have those malformed images, which does not happen on my computer (without ROS).

Maybe we should set `SteamFrameRateConstrain` in `avt_vimba_camera`. 

hen enabled, the frame rate of the camera is constrained by available bandwidth.
When disabled, the camera can image faster than it can send data.

```
When enabled, the frame rate of the camera is constrained by available bandwidth.
When disabled, the camera can image faster than it can send data.
```

It should avoid the camera to drop the end of the image if the last image is not sent yet.

**Comment by josepqp** [comment]
The nvidia jetson tx1 has an ARM 64 bits, that's why I tell you that may be it will improve.
Is the old jetson tk1 that is only 32 bits.
