### ISSUE TITLE
Default launch file for mono provide a wrong parameter

### ISSUE THREAD

**Issue by AlexisTM** [srv/avt_vimba_camera#18]
Dear,

launch file : https://github.com/srv/avt_vimba_camera/blob/kinetic/launch/mono_camera.launch#L9 

code : https://github.com/srv/avt_vimba_camera/blob/kinetic/src/mono_camera.cpp#L53

The `ip_address` is wrong. The parameter in use is `ip`, as we can see above in the code.

**Comment by miquelmassot** [comment]
Thanks! never used... I always wrote the guid
