### ISSUE TITLE
How to use a hardware trigger?

### ISSUE THREAD

**Issue by miguelriemoliveira** [srv/avt_vimba_camera#19]
Hello,

I have a stereo system with two avt cameras.

I am using this ros driver (congratullations on your work), and I was wondering if its possible that this driver works when using a hardware trigger. Is it?

If so, could you tell me what should be done in order to make it work.

Thanks,

Miguel

**Comment by miquelmassot** [comment]
That is how we connect two AVT Manta cameras, one being master (fixed fps trigger) and other being slave (Line1 trigger)

![manta_connection0](https://cloud.githubusercontent.com/assets/1611148/20477025/137c05e0-afd4-11e6-8ab6-aceb8a374632.png)

Basicaly, select "Exposing" as signal in "SyncOut1" in master camera and "Line1" as trigger source for second camera. Connect Out1 from master camera to In1 of slave camera using a pulldown resistor (check your camera hardware manual, it may be different).

And this is a part of my configuration file:

```
# Left camera parameters
# Left is master camera -> FixedRate trigger source
left_frame_id: left_optical
left_trig_timestamp_topic: ''
left_acquisition_mode: Continuous
left_acquisition_rate: 7.5
left_trigger_source: FixedRate
left_trigger_mode: On
left_trigger_selector: FrameStart
left_trigger_activation: RisingEdge
left_trigger_delay: 0
left_ptp_mode: Master
left_sync_in_selector: SyncIn1
left_sync_out_polarity: Normal
left_sync_out_selector: SyncOut1
left_sync_out_source: Exposing

# Right camera parameters
# Right is slave camera -> Line1 trigger source
right_frame_id: right_optical
right_trig_timestamp_topic: ''
right_acquisition_mode: Continuous
right_acquisition_rate: 7.5
right_trigger_source: Line1
right_trigger_mode: On
right_trigger_selector: FrameStart
right_trigger_activation: RisingEdge
right_trigger_delay: 0
right_ptp_mode: Slave
right_sync_in_selector: SyncIn1
right_sync_out_polarity: Normal
right_sync_out_selector: SyncOut1
right_sync_out_source: Exposing
```

I hope this helps!

**Comment by miguelriemoliveira** [comment]
Hi Miquel,

Thanks so much for your help. We will try it.

If we have problems we will ask you about them, in the meantime I will close the issue.

Thanks once again.

Miguel
