### ISSUE TITLE
Node crashes when it fails to find camera

### ISSUE THREAD

**Issue by shaun-edwards** [srv/avt_vimba_camera#21]
When the node fails to find the camera (in my case this happens when the camera is still powering up while ROS has already started), it crashes.  I believe this happens [here](https://github.com/srv/avt_vimba_camera/blob/9dc44cc64c58c6be5aad2b636590a24ac7eed507/src/avt_vimba_camera.cpp#L133), due to a NULL pointer being returned and not checked.

Has anybody else encountered this?  

I am running the ROS indigo version, downloaded from debs.

**Comment by miquelmassot** [comment]
Try and let me know. I'm not sure if the API shutdown & startup are necessary.
