### ISSUE TITLE
Strange image in between normal images

### ISSUE THREAD

**Issue by ykhedar** [srv/avt_vimba_camera#24]
Hi, I am using vimba ros driver for my project with Vimba G-917C color camera. I have recently observed that sometimes I get weird images in between normal ones. I am not able to figure out the reason for this. Has anyone else also experienced the same?

khedar

![manta3746](https://user-images.githubusercontent.com/8597831/26840639-0c30adaa-4ae7-11e7-9dab-b620ecb140b3.jpg)

**Comment by miquelmassot** [comment]
Does it happen with another viewer or node?

**Comment by ykhedar** [comment]
Sorry for the late response. It seems that this is an issue with the CPU not able to process the packets fast enough. I was using an Intel NUC board for processing. The issue arises only when compressed_image topic is being subscribed to which means compression of the raw image is taking place, a CPU intensive task. I observed CPU usage to go near to 100% and occurrence of this weird image becomes more frequent.  One solution for me was to lower the FPS which seems fine to me.
