### ISSUE TITLE
Binary release into ROS Kinetic

### ISSUE THREAD

**Issue by 130s** [srv/avt_vimba_camera#27]
As I mentioned in https://github.com/srv/avt_vimba_camera/pull/26, ROS pre-release test passed for ROS K (and L as well).

Thanks!

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/15785 🎆

**Comment by mikaelarguedas** [comment]
@130s @miquelmassot FYI: Looks like this fails to build on arm64 ([ubuntu xenial](http://build.ros.org/view/Lbin_uxv8_uXv8/job/Lbin_uxv8_uXv8__avt_vimba_camera__ubuntu_xenial_arm64__binary/1/) and [debian stretch](http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__avt_vimba_camera__debian_stretch_arm64__binary/1/))

**Comment by mikaelarguedas** [comment]
@miquelmassot I see that there is no libraries for `arm_64bits` in this package. Is this something that will be added in the near future ? or should this package be disabled for arm64 platforms?

**Comment by miquelmassot** [comment]
Yes please, I don't know how to disable it for arm, could you please let me
know how?

**Comment by mikaelarguedas** [comment]
Thanks for the quick reply.
Blacklisting packages for specific architectures is not something we can do through bloom and thus is an extra step after releasing.
To blacklist a package you need to open a PR on [ros_buildfarm_config](https://github.com/ros-infrastructure/ros_buildfarm_config) against the `production` branch.
In that repo there is a folder for each ROS distribution. and in each folder a set of yaml files for the different platforms/architectures. I created a PR [here](https://github.com/ros-infrastructure/ros_buildfarm_config/pull/91) to disable the package for lunar (the 2 platforms we build arm64 bit packages: Ubuntu Xenial and Debian Stretch).

Once https://github.com/ros/rosdistro/pull/15785 is merged you will need to do the same on ROS Kinetic (for Ubuntu Xenial and Debian Jessie).

Cheers!

**Comment by miquelmassot** [comment]
Thanks @mikaelarguedas, it should be solved now.

**Comment by mikaelarguedas** [comment]
@miquelmassot you will need to fix the branch name in https://github.com/ros/rosdistro/pull/15785 to point to kinetic for this package to be released in kinetic
